"""empty message

Revision ID: 56038e7ba0fe
Revises: 
Create Date: 2024-06-12 18:55:52.166079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56038e7ba0fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('collectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocated_area', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_number', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('collection_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('collection_date_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_date_id'], ['collection_dates.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_requests')
    op.drop_table('collection_dates')
    op.drop_table('households')
    op.drop_table('collectors')
    op.drop_table('admins')
    op.drop_table('users')
    # ### end Alembic commands ###
